events {
  worker_connections 1024;
}

http {
  log_format upstreamlog '$remote_addr "$request" $status upstream=$upstream_addr';
  limit_req_zone $binary_remote_addr zone=api_rate_limit:10m rate=20r/s;

  access_log /dev/stdout upstreamlog;
  error_log /dev/stderr warn;

  upstream docuscale_api {
    server api:3000;
  }

  server {
    listen 80;

    location /api/ {
      limit_req zone=api_rate_limit burst=40 nodelay;
      limit_req_status 429;

      proxy_pass http://docuscale_api;
      proxy_http_version 1.1;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_connect_timeout 5s;
      proxy_read_timeout 60s;
    }

    location / {
      proxy_pass http://docuscale_api;
      proxy_http_version 1.1;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_connect_timeout 5s;
      proxy_read_timeout 60s;
    }
  }
}
